import { Metadata } from "next";
import { Inter } from "next/font/google";
import { LayoutWidget } from "./components/widgets/LayoutWidget";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kanban App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <LayoutWidget>
          {children}
        </LayoutWidget>
      </body>
    </html>
  );
}
